### ISSUE TITLE
Add intelliJ actions

### ISSUE THREAD

**Issue by Wiesmak** [joutvhu/dart-scripts#16]
It would be nice if we could run the script as intelliJ action (e.g. as a toolbar icon)

**Comment by Wiesmak** [comment]
[documentation](https://plugins.jetbrains.com/docs/intellij/working-with-custom-actions.html)

**Comment by joutvhu** [comment]
You can run the script by Run Configuration.

![image](https://user-images.githubusercontent.com/9401202/205932450-3058cdd6-433b-48d3-bceb-7ba01ec7835d.png)

![image](https://user-images.githubusercontent.com/9401202/205933401-bc658fca-95db-4dba-b42e-fe2d1b4800a6.png)
