### ISSUE TITLE
add support for running scripts from Dart code editor

### ISSUE THREAD

**Issue by ekuleshov** [joutvhu/dart-scripts#37]
It would be really handy to be able to run dart/flutter commands from the editor. Especially when generated code needs to be updated.

For example, if a method or class doc comment has a `dart` or `flutter` command in a code block, the plugin would have a launch icon, similar to what it is there now in the `pubspec.yaml`

    /// ```
    /// dart run build_runner build --delete-conflicting-outputs
    /// ```
    @JsonSerializable()
    class CustomConfig {
       ...
    }

**Comment by joutvhu** [comment]
This feature does not bring much benefit. On the contrary, it makes the IDE slower when it has to scan too many files

**Comment by ekuleshov** [comment]
@joutvhu not sure why IDE would have to scan files to show a launch marker... We are talking about currently opened file.

The [IDEA markdown editor does that](https://www.jetbrains.com/help/idea/markdown.html#run-commands) and it is a very handy big time-saving feature. So, you don't have to copy that text, navigate to terminal, paste and run it there.

![image](https://github.com/joutvhu/dart-scripts/assets/440954/7d04d8cf-49a2-44c1-8193-a2b7dbdc808f)
